title: "Portfolio of Santiago Serrano Marco"
description: "A showcase of my projects, skills, and experience."
theme: jekyll-theme-minimal
url: "https://mili-ssm.github.io"

include:
  - Projects/
  - Pages/
  - assets/
permalink: /:path/

readme_index:
  enabled: true
  remove_originals: true

plugins:
  - jekyll-readme-index
