title: "Portfolio of Santiago Serrano Marco"
description: "A showcase of my projects, skills, and experience."
url: "https://mili-ssm.github.io"

theme: minima
plugins:
  - jekyll-feed

minima:
  skin: dark

readme_index:
  enabled: true
  remove_originals: true
  with_frontmatter: true

collections:
  projects:
    output: true
    permalink: /Projects/:name/
  pages:
    output: true
    permalink: /:name/
